### ISSUE TITLE
Update from 0.11b to 0.13b can restart Windows without prompting

### ISSUE THREAD

**Issue by agashlin** [mozilla-services/guardian-vpn-windows#4] opened 2019-12-05 21:56 UTC
I allowed 0.11b to update itself. After clicking through the UAC prompt it installed 0.13b, but then Windows restarted without prompting.

I haven't yet been able to reproduce this consistently, after encountering it on my primary laptop I had it happen in a VM, but when I restored that from a checkpoint I couldn't get it to happen again. It may have been due to something in use on the system due to long uptime? I had just switched the connection to a US server because of #3, but doing that again doesn't cause the restart, in my testing.

My main machine, where the logs below come from, is Windows 10 Pro version 1909, though the VM is Windows 10 Home 1903.

[Here's the log from the restart](https://github.com/mozilla-services/guardian-vpn-windows/files/3929126/restarted.log.txt), the many copies of the workers might be related to the many weird virtual network devices on this machine (though that wouldn't have been the issue on the VM), or is it because I have 8 cores? The only other difference I notice is that, in a run that didn't restart, "Connection/Tunnel status changing from Protected to Unprotected" was earlier in the log, before "Device closing".

[Here's the Windows restart manager event log](https://github.com/mozilla-services/guardian-vpn-windows/files/3929227/windows.logs.txt), I think the important parts are:

```
2019-12-05 09:35:38 Application 'C:\Program Files\Mozilla\Firefox Private Network VPN\FirefoxPrivateNetworkVPN.exe' (pid 4240) cannot be restarted - Application SID does not match Conductor SID..
2019-12-05 09:35:38 Application 'C:\Program Files\Mozilla\Firefox Private Network VPN\FirefoxPrivateNetworkVPN.exe' (pid 19096) cannot be restarted - Application SID does not match Conductor SID..
2019-12-05 09:35:38 Machine restart is required.
2019-12-05 09:35:47 Windows Installer requires a system restart. Product Name: Firefox Private Network VPN. Product Version: 0.13.1.1. Product Language: 1033. Manufacturer: Mozilla Corporation. Type of System Restart: 1. Reason for Restart: 1.
2019-12-05 09:35:47 The Windows Installer initiated a system restart to complete or continue the configuration of 'Firefox Private Network VPN'.
```

Those other processes that couldn't be controlled seem to be the cause, but I don't know why they'd be running under a different SID.

**Comment by agashlin** [comment] 2019-12-05 23:18
After some more testing, it looks like those two PIDs are just the normal user processes, not the SYSTEM one. It looks like most of these messages show up normally in the event log, except for the last two, "Windows Installer requires a system restart" and "The Windows Installer initiated a system restart". So I think the mystery is why Windows Installer decides to do that sometimes.

**Comment by agashlin** [comment] 2019-12-06 01:32
I got [a recording](https://github.com/mozilla-services/guardian-vpn-windows/files/3929934/update.restart.zip) of this happening in a VM, but it's still tricky to reproduce.

**Comment by connected-nkozul** [comment] 2019-12-06 19:07
Double-confirmed by @connected-crwilson . The broker process being active is the cause of this, although previously we thought it was only due to the tunnel being up. Working on it.

**Comment by connected-crwilson** [comment] 2019-12-11 15:55
This has been verified as fixed on December 10 - the client will now first disconnect the user and/or terminate the broker process before updating. Thus, the issue will now be closed.

**Closed by connected-crwilson** 2019-12-11 15:55 UTC
